// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZCz3t0CVKCLSfo717NdB6P4oX3rUrYc',
    appId: '1:663435072613:web:2ec676e9e5378b39e8a28c',
    messagingSenderId: '663435072613',
    projectId: 'pets-app-db431',
    authDomain: 'pets-app-db431.firebaseapp.com',
    storageBucket: 'pets-app-db431.appspot.com',
    measurementId: 'G-6DPT6CQK33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6ILd4X6cF2RYNCDJxfqB4pL-NTEKEjo',
    appId: '1:663435072613:android:8a1133e6ee6c7a1ce8a28c',
    messagingSenderId: '663435072613',
    projectId: 'pets-app-db431',
    storageBucket: 'pets-app-db431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfbsvGsYfFpbOXbX62us9wFawuQfHRDpM',
    appId: '1:663435072613:ios:be9684492169928ee8a28c',
    messagingSenderId: '663435072613',
    projectId: 'pets-app-db431',
    storageBucket: 'pets-app-db431.appspot.com',
    iosClientId: '663435072613-ppbog4grrih15q7kevl9j73de08m414f.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsApplication',
  );
}
